### ISSUE TITLE
Implement Trust store and Trust Policy

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/roadmap#45]
**Summary**
The user should have a way to configure the trust policy and trust store. 
**Intended Outcome**
Notation CLI implementations allows for this use case
The specification PR is merged
**Additional context**
For RC-1 the CLI commands for Trust store and Trust Policy are not mandated.

- [x] https://github.com/notaryproject/notation-go/pull/39
- [ ] Plugin Trust store and Trust Policy in CI
- [ ] Print verification output for logged level of TP

**Comment by iamsamirzon** [comment]
This is being worked upon by @rgnote

**Comment by iamsamirzon** [comment]
@dtzar  - This is ready to be closed. There are multiple PRs where this was implemented. Find links to the code below.
https://github.com/notaryproject/notation-go/blob/main/verification/policy.go
https://github.com/notaryproject/notation-go/blob/main/verification/store.go

**Comment by vaninrao10** [comment]
Need to re-open the story

**Comment by priteshbandi** [comment]
Pending tasks:

- [ ] Plugin Trust store and Trust Policy in CI
- [ ] Print verification output for logged level of TP

**Comment by iamsamirzon** [comment]
@priteshbandi , @vaninrao10 , @yizha1  - Is any work remaining for this?

**Comment by yizha1** [comment]
@iamsamirzon  I think we are done. The trust policy CLI is tracked by other roadmap issues. 

The verification output for logged level of TP is done. @priteshbandi  can you confirm this?

**Comment by iamsamirzon** [comment]
Closing this roadmap item as completed, based on above input from @yizha1  and @vaninrao10
